if(NOT MSVC)
    add_compile_options(-Wno-extra)
endif()

if(NOT DEFINED GORGONZOLA_ENABLE_ALP OR GORGONZOLA_ENABLE_ALP)
    add_subdirectory(alp)
endif()
add_subdirectory(antlr4_cypher)
add_subdirectory(antlr4_runtime)
if(NOT DEFINED GORGONZOLA_ENABLE_PARQUET OR GORGONZOLA_ENABLE_PARQUET)
    set(BROTLI_BUNDLED_MODE ON)
    add_subdirectory(brotli)
endif()
add_subdirectory(fast_float)
add_subdirectory(fastpfor)
add_subdirectory(glob)
add_subdirectory(lz4)
add_subdirectory(mbedtls)
add_subdirectory(miniz)
if(NOT DEFINED GORGONZOLA_ENABLE_PARQUET OR GORGONZOLA_ENABLE_PARQUET)
    add_subdirectory(parquet)
endif()
if(${BUILD_PYTHON})
    add_subdirectory(pybind11)
endif()
add_subdirectory(re2)
add_subdirectory(roaring_bitmap)
if(NOT DEFINED GORGONZOLA_ENABLE_SIMSIMD OR GORGONZOLA_ENABLE_SIMSIMD)
    add_subdirectory(simsimd)
endif()
if(NOT DEFINED GORGONZOLA_ENABLE_PARQUET OR GORGONZOLA_ENABLE_PARQUET)
    add_subdirectory(snappy)
    add_subdirectory(thrift)
endif()
add_subdirectory(utf8proc)
add_subdirectory(yyjson)
add_subdirectory(zstd)
if(NOT DEFINED GORGONZOLA_ENABLE_CPPJIEBA OR GORGONZOLA_ENABLE_CPPJIEBA)
    add_subdirectory(cppjieba)
endif()

# Support for OpenMP in Vector Indexing
find_package(OpenMP REQUIRED)

# simdjson integration
add_library(gorgonzola_simdjson STATIC simdjson.cpp)
target_include_directories(gorgonzola_simdjson PUBLIC .)
target_compile_features(gorgonzola_simdjson PUBLIC cxx_std_17)

# Export variables to main build tree
set(SIMDJSON_LIBRARIES gorgonzola_simdjson PARENT_SCOPE)
set(HNSWLIB_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/hnswlib PARENT_SCOPE)
